### ISSUE TITLE
Mod 'ModelShifter' (modelshifter) 1.0.1 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!

### ISSUE THREAD

**Issue by deargosep** [codingcat2468/ModelShifter#1]
![image](https://github.com/user-attachments/assets/b078f1bc-1106-4207-bfd4-827d832ebf3d)
`Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'ModelShifter' (modelshifter) 1.0.1 with any version that is compatible with:
		 - minecraft 1.21.1
More details:
	 - Mod 'ModelShifter' (modelshifter) 1.0.1 requires version 1.21 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
`

**Comment by codingcat2468** [comment]
Hi, thanks for reporting this issue! I already have a fix for this, starting with the next release there's going to be a seperate version of ModelShifter for 1.21.1, which should completely fix this problem.
